name: ADO to GitHub Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-2019
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Sync ADO to GitHub
        run: |
          $ListObject = Get-Content -Path "$($env:GITHUB_WORKSPACE)/repo-list.json" | ConvertFrom-Json
          foreach ($object in $ListObject.RepoList) {
            Write-Host "--------------- Current syncing for repo $($object.AzureRepoName) ----------------------------------"
            Set-Location $env:GITHUB_WORKSPACE
            ./ado-github-sync.sh "${{ secrets.GITHUBDESTINATIONPAT }}" "${{ secrets.ADOSOURCEPAT }}" "$($object.AzureRepoName)" "$($object.ADOCloneURL)" "$($object.GitHubCloneURL)"
            Write-Host "---------------------------------------------------------------------------------------------------"
          }
