name: ADO to GitHub Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-2019
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Sync ADO to GitHub
        run: |
          $ListObject = GC -Path "$($env:GITHUB_WORKSPACE)\repo-list.json" | ConvertFrom-Json
          Write-Host "Current directory: $PWD"
          Write-Host "ListObject: $ListObject"
          foreach ($object in $ListObject.RepoList) {
            Write-Host "--------------- Current syncing for repo $($object.AzureRepoName) ----------------------------------"
            Set-Location $($env:GITHUB_WORKSPACE)
            bash -c ./ado-github-sync.sh 
            env: 
              GITHUBDESTINATIONPAT: "${{ secrets.GITHUBDESTINATIONPAT }}" 
              ADOSOURCEPAT: "${{ secrets.ADOSOURCEPAT }}" 
              AzureRepoName "$($object.AzureRepoName)" 
              ADOCloneURL: "$($object.ADOCloneURL)" 
              GitHubCloneURL: "$($object.GitHubCloneURL)""''
            Write-Host "---------------------------------------------------------------------------------------------------"
          }
