name: ADO to GitHub Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Sync ADO to GitHub
        run: |
          ListObject=$(cat "$GITHUB_WORKSPACE/repo-list.json" | jq -r '.RepoList[] | @base64')
          echo "Current directory: $PWD"
          while IFS= read -r encodedObject; do
            object=$(echo "$encodedObject" | base64 --decode)
            AzureRepoName=$(echo "$object" | jq -r '.AzureRepoName')
            ADOCloneURL=$(echo "$object" | jq -r '.ADOCloneURL')
            GitHubCloneURL=$(echo "$object" | jq -r '.GitHubCloneURL')
            echo "--------------- Current syncing for repo $AzureRepoName ----------------------------------"
            cd "$GITHUB_WORKSPACE"
            bash ./ado-github-sync.sh "$GITHUBDESTINATIONPAT" "$ADOSOURCEPAT" "$AzureRepoName" "$ADOCloneURL" "$GitHubCloneURL"
            echo "---------------------------------------------------------------------------------------------------"
          done <<< "$ListObject"
        env:
          GITHUBDESTINATIONPAT: ${{ secrets.GITHUBDESTINATIONPAT }}
          ADOSOURCEPAT: ${{ secrets.ADOSOURCEPAT }}
